### ISSUE TITLE
Django Install Script

### ISSUE THREAD

**Issue by gustycooper** [Jeffrey-P-McAteer/gusty_nginx#1]
Create a script to take an existing Django install directory and send it to an AWS box, provisioning nginx along the way.

**Comment by Jeffrey-P-McAteer** [comment]
Good reading on github - git integration:
https://help.github.com/articles/closing-issues-via-commit-messages/
https://github.com/blog/1506-closing-issues-via-pull-requests
https://guides.github.com/features/issues/
